function [ modelname ] = create_model_name( conf, method)
%CREATE_MODEL_NAME Summary of this function goes here
%   Detailed explanation goes here
if nargin == 2
    if strcmp(method, 'kmeans')
        modelname = ['kmeans_', num2str(conf.id), ...
                       '_', conf.scene, ...
                       '_', num2str(conf.data), '_', num2str(conf.replicates)];
        return;
    elseif strcmp(method, 'spectral')
        modelname = ['spectral_', num2str(conf.id), ...
                       '_', num2str(conf.data), ...
                       '_', conf.scene, ...
                       '_',num2str(conf.replicates)];
       return;
    end
end
if conf.data ==4
    
    modelname = ['mmca_ca_', num2str(conf.id), ...
    '_', num2str(conf.clsrbalL), ...
    '_', num2str(conf.clsrbalU), ...
    '_', num2str(conf.kc), ...
    '_', num2str(conf.latent), ...
    '_', num2str(conf.feature_number), ...
    '_', num2str(conf.user_interaction), ... 
    '_', num2str(conf.num_iter), ...
    '_', num2str(conf.num_pairs), ...
    '_', num2str(conf.group_size), ...
    '_', num2str(conf.repeat), ...
    '_', num2str(conf.alpha), ];
elseif conf.data == 5
    modelname = ['mmca_nh_', num2str(conf.id), ...
    '_', num2str(conf.clsrbalL), ...
    '_', num2str(conf.clsrbalU), ...
    '_', num2str(conf.kc), ...
    '_', num2str(conf.latent), ...
    '_', num2str(conf.feature_number), ...
    '_', num2str(conf.user_interaction), ... 
    '_', num2str(conf.num_iter), ...
    '_', num2str(conf.num_pairs), ...
    '_', num2str(conf.group_size), ...
    '_', num2str(conf.repeat), ...
    '_', num2str(conf.alpha), ];
elseif conf.data == 2
    modelname = ['mmca_virat_', num2str(conf.id), ...
    '_', num2str(conf.clsrbalL), ...
    '_', num2str(conf.clsrbalU), ...
    '_', num2str(conf.kc), ...
    '_', num2str(conf.latent), ...
    '_', num2str(conf.feature_number), ...
    '_', num2str(conf.user_interaction), ... 
    '_', num2str(conf.num_iter), ...
    '_', num2str(conf.num_pairs), ...
    '_', num2str(conf.group_size), ...
    '_', num2str(conf.repeat), ...
    '_', num2str(conf.alpha), ];
else
modelname = ['mmca_', num2str(conf.id),...
    '_',num2str(conf.data), '_', num2str(conf.clsrbalL), ...
    '_', num2str(conf.clsrbalU), '_', num2str(conf.kc), '_', num2str(conf.alpha), ...
    '_', num2str(conf.randidx), '_', conf.scene, '_', num2str(conf.latent), ...
    '_', num2str(conf.latent_region), '_', num2str(conf.feature_number), ...
    '_', num2str(conf.user_interaction), '_', num2str(conf.num_iter),...
    '_', num2str(conf.num_pairs), '_', num2str(conf.group_size),...
    '_', num2str(conf.repeat)];
end
if conf.debug == 1
    modelname = [modelname '_debug'];
end

end

